services:
  - type: web
    name: tasktracker-backend
    env: node
    buildCommand: npm install
    startCommand: node server/index.ts
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: tasktracker-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: client
